### ISSUE TITLE
clarify order of assignments

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS591#26]
Heather, would you please clarify which order the assignments come?
We are currently refering to Assignment 1, 2, and so on, but the assignments now have titles.

Would you be able to respond to this issue with the numbers and their corresponding title?

**Comment by HeatherStrong11** [comment]
Yes, can you also tell me how to change the order of the assignments in the drop down menu under course assignments?  I noticed that one of the assignments is not in the right place.

**Comment by cmadland** [comment]
That happens in the ‘Menus, which you can access under the ‘Appearance’ link in the dashboard.



--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 2:46 PM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, can you also tell me how to change the order of the assignments in the drop down menu under course assignments? I noticed that one of the assignments is not in the right place.

**Comment by HeatherStrong11** [comment]
OK thanks!

**Comment by HeatherStrong11** [comment]
I have added parentheses to each assignment title to identify which assignment is 1, 2, 3, 4, 5 to help clarify.  I have also added the same information on the evaluation table under course assignments.  

I was not able to find the Appearance link option on my dashboard.  I also googled how to change the order of WP posts and I found a video that said you need to use a Plug in called post order plug in.  But I also do not have the Plug in option showing on my dashboard either.  Can you give me access to these so that I can re-arrange the order of the assignment posts?

**Comment by cmadland** [comment]
Menu is sorted.
