### ISSUE TITLE
assignment due dates

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS591#28]
When you say Jan 8 at midnight, do you mean the beginning or end of January 8?

**Comment by cmadland** [comment]
I updated the timeline with due dates set for the end of the day on Sunday.

**Comment by HeatherStrong11** [comment]
Ok, it looks like there are some differences in due dates on the WP timeline versus the timeline that I had created in gitbook.  I also can't seem to change the information on the WP timeline.  Can you adjust the dates so that they reflect what I had posted on gitbook?  I think I had to update the course syllabus so that the assignment due dates corresponded with the Learning Activities in the units.  I will send you the updated syllabus.

**Comment by cmadland** [comment]
I interpreted ‘midnight on Jan 8’ as ‘the end of the day on Jan 7’ ( those two times are one second apart). Referring to midnight will cause confusion as some will read that as the end of Jan 7 and others will read it as the end of Jan 8.

**Comment by HeatherStrong11** [comment]
Yes I see the potential problem with the time.  I think the way you have interpreted it makes sense.  The only other issue was that I don't think the due dates line up with when the assignments are assigned in the units.  For example, Assignment #1 is not assigned until the week of Jan 8th (unit 2) and the way it is set up on the timeline right now it is due just before unit 2 begins, and then assignment #2 is assigned in unit 3 and assignment 3 is assigned in unit 6 and assignment #4 is assigned in unit 9 and assignment #5 in unit 10.  I just want to make sure the timeline reflects when the assignments are assigned in the units.  Do you have any suggestions on how to make this work?

**Comment by cmadland** [comment]
Ok, no problem.

The assignments should be due at the end of the week as most students will be working on them over the weekend, then submitting files Sunday night. So, since you just sent me the weeks each assignment starts, all i need is the due dates for each one, including peer review dates.

I can update the timeline.

**Comment by HeatherStrong11** [comment]
I've adjusted a few of the learning activities so that they line up with the timeline assignment due dates.  Here are the items that need to be updated on the timeline:  
In Unit 8, I've only asked students to peer review **one** action research idea (not two). 
In Unit 9, it should say Begin Formal Literature Review Assignment (due March 23). Submit draft for peer review by March 9th.  
I think that's it.  Everything else looks good!

**Comment by cmadland** [comment]
done
